apiVersion: apps/v1
kind: Deployment
metadata:
  name: chatsv-deployment
  labels:
    app: chatsv
spec:
  replicas: 3
  selector:
    matchLabels:
      app: chatsv
  template:
    metadata:
      labels:
        app: chatsv
    spec:
      containers:
      - name: chatsv-container
        image: micakil/chat-sv:0.11
        ports:
        - containerPort: 5000