apiVersion: v1
kind: Service
metadata:
  name: chatclient-loadbalancer
  labels:
    app: chatclient
#  annotations:
#    metallb.universe.tf/loadBalancerIP: 10.230.50.2
spec:
  type: LoadBalancer
  ports:
    - port: 80
      targetPort: 3000
      protocol: TCP
  selector:
    app: chatclient
#  loadBalancerIP: 10.230.50.2