apiVersion: v1
kind: Service
metadata:
  name: chatsv-loadbalancer
  labels:
    app: chatsv
spec:
  type: LoadBalancer
  ports:
    - port: 5000
      targetPort: 5000
      protocol: TCP
  selector:
    app: chatsv