apiVersion: v1
kind: Service
metadata:
  name: chatsv-clusterip
  labels:
    app: chatsv
spec:
  type: LoadBalancer
  ports:
    - port: 5000
      targetPort: 8080
      protocol: TCP
  selector:
    app: chatsv