apiVersion: v1
kind: Service
metadata:
  name: chatclient-loadbalancer
  labels:
    app: chatclient
spec:
  type: LoadBalancer
  ports:
    - port: 80
      targetPort: 80
      protocol: TCP
  selector:
    app: chatclient