apiVersion: v1
kind: Service
metadata:
  name: chatsv-clusterip
  labels:
    app: chatsv
  annotations:
    metallb.universe.tf/loadBalancerIP: 10.230.50.4
spec:
  type: LoadBalancer
  ports:
    - port: 5000
      targetPort: 8080
      protocol: TCP
  selector:
    app: chatsv
  loadBalancerIP: 10.230.50.4