apiVersion: metallb.io/v1beta1
kind: IPAddressPool
metadata:
  name: first-pool
  namespace: metallb-system
spec:
  addresses:
    - 10.230.50.2-10.230.50.20
---
apiVersion: metallb.io/v1beta1
kind: L2Advertisement
metadata:
  name: chat
  namespace: metallb-system