apiVersion: apps/v1
kind: Deployment
metadata:
  name: redis-client
spec:
  replicas: 3
  selector:
    matchLabels:
      app: redis-client
  template:
    metadata:
      labels:
        app: redis-client
    spec:
      containers:
      - name: redis-client
        image: lucianomasuelli/redis-client:latest
        ports:
        - containerPort: 3000
---
apiVersion: v1
kind: Service
metadata:
  name: redis-client
spec:
  selector:
    app: redis-client
  ports:
  - protocol: TCP
    port: 80
    targetPort: 80
  type: LoadBalancer